version: "3.1"
volumes:
  mongo: ~
services:
  nginx:
    container_name: lk_nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
  php:
    container_name: lk_php
    build: ./docker/images/php-fpm
    working_dir: /app
    user: root
    volumes:
      - ./:/app
      - ./docker/images/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - ORACLE_HOME="/opt/oracle/instantclient_12_1"
      - LD_LIBRARY_PATH="/opt/oracle/instantclient_12_1"
    restart: always
    links:
      - mongodb
  mongodb:
    container_name: lk_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: passwd
